# Web Usage Mining

## Data Webuage

## Filter Request URI mengambil HTMLnya saja

In [ ]:
import pandas as pd

# Nama file input
file_name = "webuage.csv"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
df = pd.read_csv(file_name)

# 2. Tampilkan info untuk konfirmasi (opsional, tapi praktik yang baik)
print("\nInfo data asli:")
df.info()

# 3. Tampilkan beberapa baris pertama data asli (opsional)
print("\nData asli (head):")
print(df.head())

# 4. Tentukan kolom target
target_column = "Request URI"

# 5. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 6. Filter baris
    print(f"\nMemfilter data untuk baris di mana '{target_column}' diakhiri dengan '.html'...")
    filtered_df = df[df[target_column].str.endswith('.html', na=False)].copy()

    # 7. Simpan data yang telah difilter ke file CSV baru
    output_filename = "html_requests_only.csv"
    filtered_df.to_csv(output_filename, index=False)

    # 8. Cetak pesan sukses dan pratinjau data yang telah difilter (opsional)
    print(f"\nBerhasil memfilter data dan menyimpannya ke {output_filename}.")
    print("Pratinjau data yang telah difilter:")
    print(filtered_df.head())

Memuat data dari webuage.csv...

Info data asli:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 132258 entries, 0 to 132257
Data columns (total 9 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   Remote host                       132258 non-null  object
 1   Remote logname                    132258 non-null  object
 2   Remote user                       132258 non-null  object
 3   Request time                      132258 non-null  object
 4   Request method                    132258 non-null  object
 5   Request URI                       132258 non-null  object
 6   Request Protocol                  132258 non-null  object
 7   Status                            132258 non-null  int64
 8   Size of response (incl. headers)  132258 non-null  int64
dtypes: int64(2), object(7)
memory usage: 9.1+ MB

Data asli (head):
      Remote host Remote logname Remote user          Request time  \
0   65.55.147.227              -           -  2009-10-15T02:00:24Z
1     65.55.86.34              -           -  2009-10-15T02:00:58Z
2   148.188.55.88              -           -  2009-10-15T02:01:41Z
3    72.30.57.238              -           -  2009-10-15T02:01:59Z
4  66.249.139.233              -           -  2009-10-15T02:02:09Z

  Request method      Request URI Request Protocol  Status  \
0            GET      /index.html         HTTP/1.1     200
1            GET      /index.html         HTTP/1.1     200
2            GET        /faq.html         HTTP/1.1     200
3            GET  /contribute.txt         HTTP/1.0     200
4            GET        /faq.html         HTTP/1.1     200

   Size of response (incl. headers)
0                             21878
1                              1416
2                             10946
3                             39943
4                             17247

Memfilter data untuk baris di mana 'Request URI' diakhiri dengan '.html'...

Berhasil memfilter data dan menyimpannya ke html_requests_only.csv.
Pratinjau data yang telah difilter:
      Remote host Remote logname Remote user          Request time  \
0   65.55.147.227              -           -  2009-10-15T02:00:24Z
1     65.55.86.34              -           -  2009-10-15T02:00:58Z
2   148.188.55.88              -           -  2009-10-15T02:01:41Z
4  66.249.139.233              -           -  2009-10-15T02:02:09Z
5    72.30.50.248              -           -  2009-10-15T02:02:13Z

  Request method  Request URI Request Protocol  Status  \
0            GET  /index.html         HTTP/1.1     200
1            GET  /index.html         HTTP/1.1     200
2            GET    /faq.html         HTTP/1.1     200
4            GET    /faq.html         HTTP/1.1     200
5            GET  /index.html         HTTP/1.0     200

   Size of response (incl. headers)
0                             21878
1                              1416
2                             10946
4                             17247
5                              7883

## Filter Status mengambil nilai yg 200

In [2]:
import pandas as pd

# Nama file input (file asli)
file_name = "html_requests_only.csv"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
df = pd.read_csv(file_name)

# 2. Tentukan kolom target
target_column = "Status"

# 3. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 4. Periksa apakah kolomnya numerik sebelum membandingkan
    if pd.api.types.is_numeric_dtype(df[target_column]):

        # 5. Filter baris di mana 'Status' sama dengan 200
        print(f"\nMemfilter data untuk baris di mana '{target_column}' adalah 200...")

        # Ini adalah baris filter utamanya
        filtered_df = df[df[target_column] == 200].copy()

        # 6. Simpan data yang telah difilter ke file CSV baru
        output_filename = "status_200_only.csv"
        filtered_df.to_csv(output_filename, index=False)

        # 7. Cetak pesan sukses dan pratinjau data (opsional)
        print(f"\nBerhasil memfilter data dan menyimpannya ke {output_filename}.")
        print("Pratinjau data yang telah difilter:")
        print(filtered_df.head())
    else:
        print(f"Error: Kolom '{target_column}' bukan numerik. Tidak dapat memfilter berdasarkan nilai 200.")

Memuat data dari html_requests_only.csv...

Memfilter data untuk baris di mana 'Status' adalah 200...

Berhasil memfilter data dan menyimpannya ke status_200_only.csv.
Pratinjau data yang telah difilter:
      Remote host Remote logname Remote user          Request time  \
0   65.55.147.227              -           -  2009-10-15T02:00:24Z
1     65.55.86.34              -           -  2009-10-15T02:00:58Z
2   148.188.55.88              -           -  2009-10-15T02:01:41Z
3  66.249.139.233              -           -  2009-10-15T02:02:09Z
4    72.30.50.248              -           -  2009-10-15T02:02:13Z

  Request method  Request URI Request Protocol  Status  \
0            GET  /index.html         HTTP/1.1     200
1            GET  /index.html         HTTP/1.1     200
2            GET    /faq.html         HTTP/1.1     200
3            GET    /faq.html         HTTP/1.1     200
4            GET  /index.html         HTTP/1.0     200

   Size of response (incl. headers)
0                             21878
1                              1416
2                             10946
3                             17247
4                              7883

## Filter Request Method mengambil yg GET

In [3]:
import pandas as pd

# Nama file input (file asli)
file_name = "status_200_only.csv"
filter_value = "GET"
target_column = "Request method"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
df = pd.read_csv(file_name)

# 2. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 3. Filter baris di mana 'Request method' sama dengan 'GET'
    print(f"\nMemfilter data untuk baris di mana '{target_column}' adalah '{filter_value}'...")

    # Ini adalah baris filter utamanya
    filtered_df = df[df[target_column] == filter_value].copy()

    # 4. Simpan data yang telah difilter ke file CSV baru
    output_filename = "method_get_only.csv"
    filtered_df.to_csv(output_filename, index=False)

    # 5. Cetak pesan sukses dan pratinjau data (opsional)
    print(f"\nBerhasil memfilter data dan menyimpannya ke {output_filename}.")
    print("Pratinjau data yang telah difilter:")
    print(filtered_df.head())

Memuat data dari status_200_only.csv...

Memfilter data untuk baris di mana 'Request method' adalah 'GET'...

Berhasil memfilter data dan menyimpannya ke method_get_only.csv.
Pratinjau data yang telah difilter:
      Remote host Remote logname Remote user          Request time  \
0   65.55.147.227              -           -  2009-10-15T02:00:24Z
1     65.55.86.34              -           -  2009-10-15T02:00:58Z
2   148.188.55.88              -           -  2009-10-15T02:01:41Z
3  66.249.139.233              -           -  2009-10-15T02:02:09Z
4    72.30.50.248              -           -  2009-10-15T02:02:13Z

  Request method  Request URI Request Protocol  Status  \
0            GET  /index.html         HTTP/1.1     200
1            GET  /index.html         HTTP/1.1     200
2            GET    /faq.html         HTTP/1.1     200
3            GET    /faq.html         HTTP/1.1     200
4            GET  /index.html         HTTP/1.0     200

   Size of response (incl. headers)
0                             21878
1                              1416
2                             10946
3                             17247
4                              7883

## Merubah Request Time menjadi tanggal dan waktunya

In [10]:
import pandas as pd

# Nama file input (file asli)
file_name = "method_get_only.csv"
target_column = "Request time"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
df = pd.read_csv(file_name)
print(df.head())
# 2. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 3. Tampilkan contoh format asli (opsional)
    print(f"Format asli (baris pertama): {df[target_column].iloc[0]}")

    # 4. Lakukan transformasi:
    #    - Ganti 'T' dengan spasi
    #    - Ganti 'Z' dengan string kosong (dihapus)
    print(f"Mengubah format kolom '{target_column}'...")
    df[target_column] = df[target_column].str.replace('T', ' ', regex=False)
    df[target_column] = df[target_column].str.replace('Z', '', regex=False)

    # 5. Simpan data yang telah diubah ke file CSV baru
    output_filename = "request_time_cleaned.csv"
    df.to_csv(output_filename, index=False)

    # 6. Cetak pesan sukses dan pratinjau (opsional)
    print(f"\nBerhasil mengubah format data dan menyimpannya ke {output_filename}.")
    print("Pratinjau data yang telah diubah:")
    print(df.head())

Memuat data dari method_get_only.csv...
      Remote host Remote logname Remote user          Request time  \
0   65.55.147.227              -           -  2009-10-15T02:00:24Z
1     65.55.86.34              -           -  2009-10-15T02:00:58Z
2   148.188.55.88              -           -  2009-10-15T02:01:41Z
3  66.249.139.233              -           -  2009-10-15T02:02:09Z
4    72.30.50.248              -           -  2009-10-15T02:02:13Z

  Request method  Request URI Request Protocol  Status  \
0            GET  /index.html         HTTP/1.1     200
1            GET  /index.html         HTTP/1.1     200
2            GET    /faq.html         HTTP/1.1     200
3            GET    /faq.html         HTTP/1.1     200
4            GET  /index.html         HTTP/1.0     200

   Size of response (incl. headers)
0                             21878
1                              1416
2                             10946
3                             17247
4                              7883
Format asli (baris pertama): 2009-10-15T02:00:24Z
Mengubah format kolom 'Request time'...

Berhasil mengubah format data dan menyimpannya ke request_time_cleaned.csv.
Pratinjau data yang telah diubah:
      Remote host Remote logname Remote user         Request time  \
0   65.55.147.227              -           -  2009-10-15 02:00:24
1     65.55.86.34              -           -  2009-10-15 02:00:58
2   148.188.55.88              -           -  2009-10-15 02:01:41
3  66.249.139.233              -           -  2009-10-15 02:02:09
4    72.30.50.248              -           -  2009-10-15 02:02:13

  Request method  Request URI Request Protocol  Status  \
0            GET  /index.html         HTTP/1.1     200
1            GET  /index.html         HTTP/1.1     200
2            GET    /faq.html         HTTP/1.1     200
3            GET    /faq.html         HTTP/1.1     200
4            GET  /index.html         HTTP/1.0     200

   Size of response (incl. headers)
0                             21878
1                              1416
2                             10946
3                             17247
4                              7883

## Filter Berdasarkan IP Address(Remote host) dan User Agent(Request Protocol)

In [16]:
import pandas as pd

# Nama file input
file_name = "request_time_cleaned.csv"

print(f"Memuat data dari {file_name}...")
try:
    # Dataset Anda memakai koma sebagai pemisah kolom
    df = pd.read_csv(file_name, sep=',')
except FileNotFoundError:
    print(f"Error: File {file_name} tidak ditemukan.")
    exit()

# Nama kolom sesuai dataset asli NASA
col_ip = "Remote host"
col_datetime = "Request time"
new_col_name = "SESSION"

# Periksa apakah kolom tersedia
if col_ip in df.columns and col_datetime in df.columns:

    print("Mengubah kolom 'Request time' menjadi format datetime...")

    # Konversi ke datetime
    df[col_datetime] = pd.to_datetime(df[col_datetime], errors='coerce')

    # Tambahkan kolom tanggal dan waktu
    df["tanggal"] = df[col_datetime].dt.date.astype(str)
    df["waktu"] = df[col_datetime].dt.time.astype(str)

    print(f"Membuat kolom '{new_col_name}' berdasarkan IP unik...")

    # SESSION berdasarkan host unik
    df[new_col_name] = df[col_ip].astype("category").cat.codes + 1

    print("Mengurutkan data berdasarkan SESSION dan waktu...")
    df_sorted = df.sort_values(by=[new_col_name, col_datetime])

    # Simpan hasil
    output_filename = "data_filtered.csv"
    df_sorted.to_csv(output_filename, index=False)

    print(f"\nBerhasil! Kolom '{new_col_name}' telah ditambahkan.")
    print(f"File baru disimpan sebagai: {output_filename}")
    print("\nPratinjau data:")
    print(df_sorted.head())

else:
    print(f"Error: Kolom '{col_ip}' atau '{col_datetime}' tidak ditemukan pada dataset.")

Memuat data dari request_time_cleaned.csv...
Mengubah kolom 'Request time' menjadi format datetime...
Membuat kolom 'SESSION' berdasarkan IP unik...
Mengurutkan data berdasarkan SESSION dan waktu...

Berhasil! Kolom 'SESSION' telah ditambahkan.
File baru disimpan sebagai: data_filtered.csv

Pratinjau data:
           Remote host Remote logname Remote user        Request time  \
36189  109.192.104.209              -           - 2009-10-18 18:27:27
36190   109.192.104.86              -           - 2009-10-18 18:27:27
36171  109.192.109.233              -           - 2009-10-18 18:26:27
36818  109.192.111.243              -           - 2009-10-18 20:59:37
36177  109.192.117.151              -           - 2009-10-18 18:26:27

      Request method  Request URI Request Protocol  Status  \
36189            GET  /index.html         HTTP/1.1     200
36190            GET  /index.html         HTTP/1.1     200
36171            GET    /faq.html         HTTP/1.1     200
36818            GET  /index.html         HTTP/1.1     200
36177            GET  /index.html         HTTP/1.1     200

       Size of response (incl. headers)     tanggal     waktu  SESSION
36189                             19395  2009-10-18  18:27:27        1
36190                             99209  2009-10-18  18:27:27        2
36171                               757  2009-10-18  18:26:27        3
36818                             10937  2009-10-18  20:59:37        4
36177                               285  2009-10-18  18:26:27        5

## Dataset NASA

## Filter link web HTML

In [1]:
import pandas as pd

# Nama file input
file_name = "data.csv"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
# DIUBAH: Tambahkan sep=';' karena file Anda menggunakan titik koma
# DIUBAH: Tambahkan index_col=0 karena kolom pertama adalah indeks
df = pd.read_csv(file_name, sep=';', index_col=0)

# 2. Tampilkan info untuk konfirmasi (opsional)
print("\nInfo data asli:")
df.info()

# 3. Tampilkan beberapa baris pertama data asli (opsional)
print("\nData asli (head):")
print(df.head())

# 4. Tentukan kolom target
# DIUBAH: Kita mencari .html di kolom 'url', bukan 'host'
target_column = "url"

# 5. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 6. Filter baris
    #    Logika ini sekarang akan diterapkan pada kolom 'url'
    print(f"\nMemfilter data untuk baris di mana '{target_column}' diakhiri dengan '.html'...")
    filtered_df = df[df[target_column].str.endswith('.html', na=False)].copy()

    # 7. Simpan data yang telah difilter ke file CSV baru
    output_filename = "html_requests_only_NASA.csv"
    # DIUBAH: Tambahkan sep=';' saat menyimpan agar konsisten
    filtered_df.to_csv(output_filename, sep=';')

    # 8. Cetak pesan sukses dan pratinjau data yang telah difilter
    print(f"\nBerhasil memfilter data dan menyimpannya ke {output_filename}.")
    print("Pratinjau data yang telah difilter:")
    print(filtered_df.head())

Memuat data dari data.csv...

C:\Users\Mukti Hendra\AppData\Local\Temp\ipykernel_5700\3944447601.py:10: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name, sep=';', index_col=0)

Info data asli:
<class 'pandas.core.frame.DataFrame'>
Index: 1048575 entries, 0 to 1048574
Data columns (total 6 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   host      1048575 non-null  object
 1   time      1048575 non-null  int64
 2   method    1048575 non-null  object
 3   url       1048575 non-null  object
 4   response  1048575 non-null  int64
 5   bytes     1048575 non-null  int64
dtypes: int64(3), object(3)
memory usage: 56.0+ MB

Data asli (head):
          host       time method                           url  response  \
0  ***.novo.dk  805465029    GET                     /ksc.html       200
1  ***.novo.dk  805465031    GET    /images/ksclogo-medium.gif       200
2  ***.novo.dk  805465051    GET  /images/MOSAIC-logosmall.gif       200
3  ***.novo.dk  805465053    GET     /images/USA-logosmall.gif       200
4  ***.novo.dk  805465054    GET    /images/NASA-logosmall.gif       200

   bytes
0   7067
1   5866
2    363
3    234
4    786

Memfilter data untuk baris di mana 'url' diakhiri dengan '.html'...

Berhasil memfilter data dan menyimpannya ke html_requests_only_NASA.csv.
Pratinjau data yang telah difilter:
           host       time method  \
0   ***.novo.dk  805465029    GET
6   ***.novo.dk  805465068    GET
12  ***.novo.dk  805465381    GET
13  ***.novo.dk  807951768    GET
23  ***.novo.dk  807951938    GET

                                             url  response  bytes
0                                      /ksc.html       200   7067
6                /shuttle/missions/missions.html       200   8678
12     /shuttle/resources/orbiters/columbia.html       200   6922
13  /shuttle/missions/sts-69/mission-sts-69.html       200  11264
23               /shuttle/countdown/liftoff.html       200   4665

## Filter Status mengambil nilai yg 200

In [2]:
import pandas as pd

# Nama file input (file dari langkah sebelumnya)
file_name = "html_requests_only_NASA.csv"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
# DIUBAH: Tambahkan sep=';' untuk membaca file dengan benar
df = pd.read_csv(file_name, sep=';')

# 2. Tentukan kolom target
target_column = "response"

# 3. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 4. Periksa apakah kolomnya numerik (sekarang seharusnya berhasil)
    if pd.api.types.is_numeric_dtype(df[target_column]):

        # 5. Filter baris di mana 'response' sama dengan 200
        print(f"\nMemfilter data untuk baris di mana '{target_column}' adalah 200...")

        # Ini adalah baris filter utama (logika Anda sudah benar)
        filtered_df = df[df[target_column] == 200].copy()

        # 6. Simpan data yang telah difilter ke file CSV baru
        output_filename = "status_200_only_NASA.csv"
        # DIUBAH: Tambahkan sep=';' agar konsisten saat menyimpan
        filtered_df.to_csv(output_filename, index=False, sep=';')

        # 7. Cetak pesan sukses dan pratinjau data
        print(f"\nBerhasil memfilter data dan menyimpannya ke {output_filename}.")
        print("Pratinjau data yang telah difilter:")
        print(filtered_df.head())
    else:
        # (Jika sep=';' lupa ditambahkan, Anda mungkin akan melihat error ini)
        print(f"Error: Kolom '{target_column}' bukan numerik. Periksa pemisah file CSV.")

Memuat data dari html_requests_only_NASA.csv...

C:\Users\Mukti Hendra\AppData\Local\Temp\ipykernel_5700\1600313524.py:9: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name, sep=';')

Memfilter data untuk baris di mana 'response' adalah 200...

Berhasil memfilter data dan menyimpannya ke status_200_only_NASA.csv.
Pratinjau data yang telah difilter:
  Unnamed: 0         host       time method  \
0          0  ***.novo.dk  805465029    GET
1          6  ***.novo.dk  805465068    GET
2         12  ***.novo.dk  805465381    GET
3         13  ***.novo.dk  807951768    GET
4         23  ***.novo.dk  807951938    GET

                                            url  response  bytes
0                                     /ksc.html       200   7067
1               /shuttle/missions/missions.html       200   8678
2     /shuttle/resources/orbiters/columbia.html       200   6922
3  /shuttle/missions/sts-69/mission-sts-69.html       200  11264
4               /shuttle/countdown/liftoff.html       200   4665

## Filter Request Method mengambil yg GET

In [3]:
import pandas as pd

# Nama file input (file dari langkah sebelumnya)
file_name = "status_200_only_NASA.csv"
filter_value = "GET"
# DIUBAH: Nama kolom yang benar adalah 'method', bukan 'Request method'
target_column = "method"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
# DIUBAH: Tambahkan sep=';' untuk membaca file dengan benar
df = pd.read_csv(file_name, sep=';')

# 2. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 3. Filter baris di mana 'method' sama dengan 'GET'
    print(f"\nMemfilter data untuk baris di mana '{target_column}' adalah '{filter_value}'...")

    # Ini adalah baris filter utama (Logika Anda sudah benar)
    filtered_df = df[df[target_column] == filter_value].copy()

    # 4. Simpan data yang telah difilter ke file CSV baru
    output_filename = "method_get_only_NASA.csv"
    # DIUBAH: Tambahkan sep=';' agar konsisten saat menyimpan
    filtered_df.to_csv(output_filename, index=False, sep=';')

    # 5. Cetak pesan sukses dan pratinjau data (opsional)
    print(f"\nBerhasil memfilter data dan menyimpannya ke {output_filename}.")
    print("Pratinjau data yang telah difilter:")
    print(filtered_df.head())

Memuat data dari status_200_only_NASA.csv...

Memfilter data untuk baris di mana 'method' adalah 'GET'...

C:\Users\Mukti Hendra\AppData\Local\Temp\ipykernel_5700\3473009687.py:12: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name, sep=';')

Berhasil memfilter data dan menyimpannya ke method_get_only_NASA.csv.
Pratinjau data yang telah difilter:
  Unnamed: 0         host       time method  \
0          0  ***.novo.dk  805465029    GET
1          6  ***.novo.dk  805465068    GET
2         12  ***.novo.dk  805465381    GET
3         13  ***.novo.dk  807951768    GET
4         23  ***.novo.dk  807951938    GET

                                            url  response  bytes
0                                     /ksc.html       200   7067
1               /shuttle/missions/missions.html       200   8678
2     /shuttle/resources/orbiters/columbia.html       200   6922
3  /shuttle/missions/sts-69/mission-sts-69.html       200  11264
4               /shuttle/countdown/liftoff.html       200   4665

## Merubah Request Time menjadi tanggal dan waktunya

In [4]:
import pandas as pd

# DIUBAH: Nama file input yang benar
file_name = "method_get_only_NASA.csv"
# DIUBAH: Nama kolom target yang benar
target_column = "time"

# 1. Muat dataset
print(f"Memuat data dari {file_name}...")
# DIUBAH: Tambahkan sep=';' untuk membaca file dengan benar
df = pd.read_csv(file_name, sep=';')

# 2. Periksa apakah kolom target ada
if target_column not in df.columns:
    print(f"Error: Kolom '{target_column}' tidak ditemukan di CSV.")
else:
    # 3. Tampilkan contoh format asli (ini adalah Angka/Timestamp)
    print(f"Format asli (baris pertama): {df[target_column].iloc[0]}")

    # 4. Lakukan transformasi:
    #    Kita tidak mengganti 'T' atau 'Z' karena data aslinya adalah angka (Unix timestamp).
    #    Kita akan MENGONVERSI timestamp itu ke format datetime yang mudah dibaca.
    print(f"Mengonversi kolom '{target_column}' (Unix timestamp) ke format Datetime...")

    # pd.to_datetime mengonversi angka timestamp (unit='s' berarti 'seconds')
    # Kita buat kolom baru 'datetime_readable' agar data asli tidak hilang
    df['datetime_readable'] = pd.to_datetime(df[target_column], unit='s')

    # 5. Simpan data yang telah diubah ke file CSV baru
    output_filename = "time_converted_NASA.csv"
    # DIUBAH: Tambahkan sep=';' agar konsisten
    df.to_csv(output_filename, index=False, sep=';')

    # 6. Cetak pesan sukses dan pratinjau
    print(f"\nBerhasil mengonversi data waktu dan menyimpannya ke {output_filename}.")
    print("Pratinjau data yang telah diubah (lihat kolom baru 'datetime_readable'):")
    print(df.head())

Memuat data dari method_get_only_NASA.csv...
Format asli (baris pertama): 805465029
Mengonversi kolom 'time' (Unix timestamp) ke format Datetime...

C:\Users\Mukti Hendra\AppData\Local\Temp\ipykernel_5700\3743564732.py:11: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name, sep=';')

Berhasil mengonversi data waktu dan menyimpannya ke time_converted_NASA.csv.
Pratinjau data yang telah diubah (lihat kolom baru 'datetime_readable'):
  Unnamed: 0         host       time method  \
0          0  ***.novo.dk  805465029    GET
1          6  ***.novo.dk  805465068    GET
2         12  ***.novo.dk  805465381    GET
3         13  ***.novo.dk  807951768    GET
4         23  ***.novo.dk  807951938    GET

                                            url  response  bytes  \
0                                     /ksc.html       200   7067
1               /shuttle/missions/missions.html       200   8678
2     /shuttle/resources/orbiters/columbia.html       200   6922
3  /shuttle/missions/sts-69/mission-sts-69.html       200  11264
4               /shuttle/countdown/liftoff.html       200   4665

    datetime_readable
0 1995-07-11 12:17:09
1 1995-07-11 12:17:48
2 1995-07-11 12:23:01
3 1995-08-09 07:02:48
4 1995-08-09 07:05:38

## Filter Berdasarkan IP Address(host) dan User Agent(Request Protocol)

In [ ]:
import pandas as pd

# 1. Tentukan file input (file yang memiliki 'datetime_readable')
file_name = "time_converted_NASA.csv"

# 2. Tentukan kolom-kolom yang akan kita gunakan
col_ip = "host"               # Kolom untuk mengelompokkan sesi
col_time = "datetime_readable" # Kolom untuk mengurutkan sesi
new_col_name = "SESSION"      # Nama kolom sesi baru

print(f"Memuat data dari {file_name}...")
try:
    # 3. Muat dataset
    # PENTING: Kita gunakan parse_dates=[col_time]
    # agar pandas langsung membacanya sebagai objek datetime
    df = pd.read_csv(file_name, sep=';', parse_dates=[col_time])
except FileNotFoundError:
    print(f"Error: File {file_name} tidak ditemukan.")
    print("Pastikan Anda sudah menjalankan skrip konversi 'time' sebelumnya.")
    exit()
except ValueError as e:
    print(f"Error saat membaca {file_name}. Cek kolom '{col_time}'.")
    print(f"Detail: {e}")
    exit()


# 4. Periksa apakah kolom yang diperlukan ada
if col_ip in df.columns and col_time in df.columns:

    # 5. BUAT KOLOM SESSION (Logika yang sama seperti sebelumnya)
    print(f"Membuat kolom '{new_col_name}' berdasarkan '{col_ip}' unik...")
    df[new_col_name] = df[col_ip].astype('category').cat.codes + 1

    # 6. Urutkan data berdasarkan SESSION, lalu WAKTU
    print(f"Mengurutkan data berdasarkan '{new_col_name}' dan '{col_time}'...")
    df_sorted = df.sort_values(by=[new_col_name, col_time], ascending=True)

    # 7. Hapus kolom 'time' (timestamp angka) yang asli agar rapi
    if 'time' in df_sorted.columns:
        print("Menghapus kolom 'time' (timestamp unix) asli...")
        df_sorted = df_sorted.drop(columns=['time'])

    # 8. Simpan DataFrame LENGKAP yang sudah diurutkan
    output_filename = "session_data_full_NASA.csv"

    # --- INI YANG DIUBAH ---
    # Kita ubah sep=';' (titik-koma) menjadi sep=',' (koma)
    print(f"Menyimpan data ke {output_filename} dengan pemisah KOMA (',')...")
    df_sorted.to_csv(output_filename, index=False, sep=',')
    # -------------------------

    print(f"\nBerhasil! Kolom '{new_col_name}' telah ditambahkan.")
    print(f"File baru disimpan sebagai: {output_filename}")
    print("\nPratinjau data baru (menampilkan kolom yang Anda minta):")

    # Tampilkan pratinjau hanya dengan kolom yang diminta agar mudah dilihat
    preview_cols = [new_col_name, col_ip, col_time, 'url']
    print(df_sorted[preview_cols].head())

else:
    print(f"Error: Kolom '{col_ip}' atau '{col_time}' tidak ditemukan di {file_name}.")

Memuat data dari time_converted_NASA.csv...

C:\Users\Mukti Hendra\AppData\Local\Temp\ipykernel_5700\1479576779.py:16: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name, sep=';', parse_dates=[col_time])

Membuat kolom 'SESSION' berdasarkan 'host' unik...
Mengurutkan data berdasarkan 'SESSION' dan 'datetime_readable'...
Menghapus kolom 'time' (timestamp unix) asli...
Menyimpan data ke session_data_full_NASA.csv dengan pemisah KOMA (',')...

Berhasil! Kolom 'SESSION' telah ditambahkan.
File baru disimpan sebagai: session_data_full_NASA.csv

Pratinjau data baru (menampilkan kolom yang Anda minta):
   SESSION         host   datetime_readable  \
0        1  ***.novo.dk 1995-07-11 12:17:09
1        1  ***.novo.dk 1995-07-11 12:17:48
2        1  ***.novo.dk 1995-07-11 12:23:01
3        1  ***.novo.dk 1995-08-09 07:02:48
4        1  ***.novo.dk 1995-08-09 07:05:38

                                            url
0                                     /ksc.html
1               /shuttle/missions/missions.html
2     /shuttle/resources/orbiters/columbia.html
3  /shuttle/missions/sts-69/mission-sts-69.html
4               /shuttle/countdown/liftoff.html

In [10]:
import pandas as pd
file_name = "session_data_full_NASA.csv"
df = pd.read_csv(file_name)

url_col = None
for col in df.columns:
    if 'url' in col.lower():
        url_col = col
        break

df['URL_ID'] = df[url_col].astype('category').cat.codes

# =====================
# 3. Buat index user dari Unnamed + Host
# =====================
df['USER_KEY'] = df['Unnamed: 0'].astype(str) + "-" + df['host'].astype(str)

# =====================
# 4. Crosstab biner
# =====================
binary_matrix = pd.crosstab(df['USER_KEY'], df['URL_ID'])

# =====================
# 5. Tampilkan hasil
# =====================
binary_matrix.head(50)

C:\Users\Mukti Hendra\AppData\Local\Temp\ipykernel_20204\651504668.py:3: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_name)

URL_ID,0,1,2,3,4,5,6,7,8,9,...,102,103,104,105,106,107,108,109,110,111
USER_KEY,,,,,,,,,,,,,,,,,,,,,
0-***.novo.dk,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000-118.32.med.umich.edu,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000000-cft4.ppp250.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000004-cft4.ppp252.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000008-cft4.ppp252.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000009-cft4.ppp252.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100002-128.217.62.100,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000021-cft4.ppp252.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000034-cft4.ppp253.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000038-cft4.ppp253.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000042-cft4.ppp253.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000047-cft4.ppp253.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000049-cft4.ppp253.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000051-cft4.ppp253.cftnet.com,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000053-cft4.ppp253.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000056-cft6.ppp241.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000059-cft6.ppp241.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000060-cft6.ppp241.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1000061-cft6.ppp241.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000063-cft6.ppp241.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000065-cft6.ppp244.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000077-cft6.ppp246.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100008-128.217.62.100,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000081-cft6.ppp246.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000085-cft6.ppp248.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000092-cft6.ppp248.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000097-cft6.ppp250.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000098-cft6.ppp250.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000102-cft6.ppp251.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000106-cft6.ppp252.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000112-cft6.ppp252.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000116-cft6.ppp253.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000118-cft6.ppp253.cftnet.com,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000119-cft6.ppp253.cftnet.com,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000121-cft6.ppp253.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000123-cft6.ppp253.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000128-cft6.ppp253.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000129-cft6.ppp253.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000138-cft6.ppp253.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100014-128.217.62.100,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000140-cft6.ppp253.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000149-cft6.ppp253.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000154-cft6.ppp253.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000157-cft6.ppp253.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000158-cft6.ppp253.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000160-cft6.ppp253.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000162-cft6.ppp253.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000165-cft6.ppp253.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000166-cft6.ppp253.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1000174-cft6.ppp253.cftnet.com,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
url_col = None
for col in df.columns:
    if "url" in col.lower():
        url_col = col
        break

if url_col is None:
    raise ValueError("Kolom URL tidak ditemukan dalam dataset.")

# =========================================
# 3. Hitung jumlah segmen (page) dari URL
# =========================================
# Contoh:
# "/shuttle/missions/missions.html" -> 3
df['URL_SEGMENT_COUNT'] = df[url_col].apply(
    lambda x: len([p for p in str(x).split('/') if p])
)

# =========================================
# 4. Buat ID unik berdasarkan segmen
# =========================================
df['URL_DEPTH_ID'] = df['URL_SEGMENT_COUNT'].astype('category').cat.codes

# =========================================
# 5. Tampilkan contoh hasil
# =========================================
df[[url_col, 'URL_SEGMENT_COUNT', 'URL_DEPTH_ID']].head(20)

,url,URL_SEGMENT_COUNT,URL_DEPTH_ID
0,/ksc.html,1,0
1,/shuttle/missions/missions.html,3,2
2,/shuttle/resources/orbiters/columbia.html,4,3
3,/shuttle/missions/sts-69/mission-sts-69.html,4,3
4,/shuttle/countdown/liftoff.html,3,2
5,/shuttle/countdown/lps/fr.html,4,3
6,/software/winvn/winvn.html,3,2
7,/shuttle/missions/sts-71/mission-sts-71.html,4,3
8,/shuttle/missions/sts-71/mission-sts-71.html,4,3
9,/shuttle/missions/sts-71/images/images.html,5,4
10,/shuttle/countdown/tour.html,3,2
11,/shuttle/missions/sts-71/movies/movies.html,5,4
12,/history/history.html,2,1
13,/shuttle/missions/missions.html,3,2
14,/shuttle/missions/sts-71/mission-sts-71.html,4,3
15,/ksc.html,1,0
16,/shuttle/countdown/countdown.html,3,2
17,/shuttle/countdown/count.html,3,2
18,/shuttle/countdown/liftoff.html,3,2
19,/shuttle/countdown/lps/fr.html,4,3

In [13]:
# Baca CSV (hindari warning)
df = pd.read_csv(file_name, low_memory=False)

# =========================================
# 2. Deteksi kolom URL
# =========================================
url_col = None
for col in df.columns:
    if "url" in col.lower():
        url_col = col
        break

if url_col is None:
    raise ValueError("Kolom URL tidak ditemukan dalam dataset.")

# =========================================
# 3. Buat ID unik untuk setiap URL lengkap
# =========================================
df['URL_ID'] = df[url_col].astype('category').cat.codes

# =========================================
# 4. Tampilkan contoh 20 baris pertama
# =========================================
df[[url_col, 'URL_ID']].head(20)
print(len(url_col))

3